// <auto-generated />
using System;
using MedicalBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalBookingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409174608_AddPrescriptionToMedicalRecord")]
    partial class AddPrescriptionToMedicalRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalBookingAPI.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "AppointmentTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Tim mạch",
                            Description = "Khoa Tim mạch - Chẩn đoán và điều trị các bệnh lý tim mạch"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Thần kinh",
                            Description = "Khoa Thần kinh - Điều trị các bệnh lý thần kinh và não bộ"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Tiêu hóa",
                            Description = "Khoa Tiêu hóa - Điều trị các bệnh lý đường tiêu hóa"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Hô hấp",
                            Description = "Khoa Hô hấp - Điều trị các bệnh lý đường hô hấp"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Tai mũi họng",
                            Description = "Khoa Tai mũi họng - Điều trị các bệnh lý tai, mũi, họng"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Da liễu",
                            Description = "Khoa Da liễu - Điều trị các bệnh lý da và các bệnh lây truyền qua đường tình dục"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Cơ xương khớp",
                            Description = "Khoa Cơ xương khớp - Điều trị các bệnh lý cơ, xương, khớp"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Nội tổng quát",
                            Description = "Khoa Nội tổng quát - Khám và điều trị các bệnh nội khoa tổng hợp"
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentName = "Nhi khoa",
                            Description = "Khoa Nhi khoa - Chăm sóc sức khỏe trẻ em từ sơ sinh đến 15 tuổi"
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentName = "Sản phụ khoa",
                            Description = "Khoa Sản phụ khoa - Chăm sóc sức khỏe phụ nữ và sinh sản"
                        });
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            DepartmentId = 1,
                            Qualification = "Bác sĩ chuyên khoa",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalRecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DoctorDiagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "Male",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@medical.com",
                            FullName = "Quản trị viên",
                            PasswordHash = "$2a$11$P8U93igOYHagj91dHEXW4ev7FS0742kYUdin69Xx.jOng3ATszagC",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor@medical.com",
                            FullName = "Bác sĩ Trương",
                            PasswordHash = "$2a$11$LywSnU/stisjWCB.Nko3bubrraBHtdIMmxrPRMgdGzzXPI4BBu1Hq",
                            Phone = "9876543210",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient@medical.com",
                            FullName = "Đỗ Minh Quân",
                            PasswordHash = "$2a$11$Bfy7mFlEdyemUrsz91dHT./3HxJM3IvcAE9xo7s1xavClQ0mAqsP6",
                            Phone = "0123456789",
                            Role = "Patient"
                        });
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Appointment", b =>
                {
                    b.HasOne("MedicalBookingAPI.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalBookingAPI.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Doctor", b =>
                {
                    b.HasOne("MedicalBookingAPI.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalBookingAPI.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MedicalBookingAPI.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.MedicalRecord", b =>
                {
                    b.HasOne("MedicalBookingAPI.Entities.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("MedicalBookingAPI.Entities.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Patient", b =>
                {
                    b.HasOne("MedicalBookingAPI.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("MedicalBookingAPI.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MedicalBookingAPI.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
